# CentOS 7 yum dependencies
# yum install --enablerepo="base" libevent-devel automake bison ncurses-devel git

    - hosts: myservers
      #connection: local
      tasks: 

        - name: TMUX 2 Download
          git:
              repo: 'https://github.com/tmux/tmux.git'
              clone: yes
              dest: "./github/tmux/"

        - name: TMUX Build 
          command: sh ./autogen.sh
          args: 
            chdir: ./github/tmux/

        - name: TMUX Configure
          command: ./configure --prefix={{ansible_env.HOME}}/tmux-2.x/
          args: 
            chdir: ./github/tmux/

        - name: TMUX Make Install
          command: make install
          args: 
            chdir: ./github/tmux/

        - name: Create bh Directory
          ansible.builtin.file: 
            path: "{{ ansible_env.HOME }}/bh/"
            state: directory

        - name: Copy Conf 3 File
          ansible.builtin.copy: 
            src: "{{ playbook_dir }}/tmux3.conf"
            dest: "{{ ansible_env.HOME }}/bh/tmux3.conf"

        - name: Copy Conf 1 File
          ansible.builtin.copy: 
            src: "{{ playbook_dir }}/tmux1.conf"
            dest: "{{ ansible_env.HOME }}/bh/tmux1.conf"

        #- name: Install TMUX conf file
        #  file: 
        #    state: link
        #    src: "{{ playbook_dir }}/.tmux.conf"
        #    path: "{{ ansible_env.HOME }}/.tmux.conf"
        #    force: yes

