#f20 dependencies: 
#httpd httpd-tools libX11-devel libXtst-devel libXt-devel libSM-devel libXpm-devel ncurses-devel python2-devel gtk2-devel ruby-devel python3-devel cmake
#centos dependencies: 
#httpd httpd-tools libX11-devel libXtst-devel libXt-devel libSM-devel libXpm-devel ncurses-devel python2-devel gtk2-devel ruby-devel python36-devel cmake

#Add this to your .bashrc to enable this version of vim: 
#export PATH=${HOME}/vim-8.x/bin/:${PATH}
    - hosts: myservers
      #connection: local
      vars:
        vim_start_path: "{{ ansible_env.HOME }}/.vim/pack/default/start/"
        command_t_ext_dir: "{{ vim_start_path }}/command-t/ruby/command-t/ext/command-t/"
      tasks: 

        - name: Install dependencies
          apt:
              name:
                 - ruby-dev
                 - make
          when:
             - ansible_distribution == "Ubuntu"
             #- ansible_distribution == "CentOS"
        - name: VIM Plugin gruvbox Git Clone
          git:
              repo: 'https://github.com/morhetz/gruvbox.git'
              clone: yes
              dest: "{{ vim_start_path }}/gruvbox"
              depth: 1
              version: 'v3.0.1-rc.0' #Disable 'version' field if you want to get the latest

        - name: VIM Plugin airline Git Clone
          git:
              repo: 'https://github.com/vim-airline/vim-airline.git'
              clone: yes
              dest: "{{ vim_start_path }}/airline"
              depth: 1
              version: 'v0.10' #Disable 'version' field if you want to get the latest

        - name: VIM Plugin command-t Git Clone
          git:
              repo: 'https://github.com/wincent/command-t.git'
              clone: yes
              dest: "{{ vim_start_path }}/command-t"
              depth: 1
              version: '5.0.3' #Disable 'version' field if you want to get the latest

#For Mac need to specify the homebrew version of ruby instead of the system one
        - name: VIM Plugin command-t install
          command: ruby extconf.rb
          args:
            chdir: "{{ command_t_ext_dir }}"

        - name: VIM Plugin command-t make
          command: make
          args:
            chdir: "{{ command_t_ext_dir }}"

        - name: VIM Plugin vim-illuminate Git Clone
          git:
              repo: 'https://github.com/RRethy/vim-illuminate.git'
              clone: yes
              dest: "{{ vim_start_path }}/vim-illuminate"
              depth: 1
              #version: '9dee2b4e3f5de5f8b9fdc4790eac35eb2c40257a' #Disable 'version' field if you want to get the latest

        - name: VIM Plugin Fugitive Git Clone
          git:
              repo: 'https://github.com/tpope/vim-fugitive.git'
              clone: yes
              dest: "{{ vim_start_path }}/vim-fugitive"
              depth: 1

        - name: Create bh Directory
          ansible.builtin.file: 
            path: "{{ ansible_env.HOME }}/bh/"
            state: directory

        - name: Copy Conf File 1
          ansible.builtin.copy: 
            src: "{{ playbook_dir }}/vimrc"
            dest: "{{ ansible_env.HOME }}/bh/"

        - name: Copy Conf File 2
          ansible.builtin.copy: 
            src: "{{ playbook_dir }}/cscope_maps.vim"
            dest: "{{ ansible_env.HOME }}/bh/"
            

