#f20 dependencies: 
#httpd httpd-tools libX11-devel libXtst-devel libXt-devel libSM-devel libXpm-devel ncurses-devel python2-devel gtk2-devel ruby-devel python3-devel cmake
#centos dependencies: 
#yum install --enablerepo="base,updates" httpd httpd-tools libX11-devel libXtst-devel libXt-devel libSM-devel libXpm-devel ncurses-devel python2-devel gtk2-devel ruby-devel python36-devel cmake git

#Add this to your .bashrc to enable this version of vim: 
#export PATH=${HOME}/vim-8.x/bin/:${PATH}
    - hosts: myservers
      #connection: local
      vars:
        vim_start_path: "{{ ansible_env.HOME }}/.vim/pack/default/start/"
        command_t_ext_dir: "{{ vim_start_path }}/command-t/ruby/command-t/ext/command-t/"
      tasks: 

        - name: Download VIM 8.x
          git:
              repo: 'https://github.com/vim/vim.git'
              clone: yes
              dest: './github/vim'
              depth: 1
              #version: 'v8.1.1142' #Disable if you want the latest

        - name: Getting python config directory
          shell: python3 -c "import sysconfig; print(sysconfig.get_config_var('LIBPL'))"
          register: py_config_dir_output

        - name: Display the output
          debug:
            msg: "Python config directory: {{ py_config_dir_output.stdout }}"

        - name: Configure VIM
          command: ./configure --prefix={{ansible_env.HOME}}/vim-8.x/ --enable-rubyinterp=yes --enable-python3interp=yes --with-python3-config-dir={{ py_config_dir_output.stdout }} --enable-gui=gtk2 --enable-gnome-check --with-x
            
          args: 
            chdir: ./github/vim/
            creates: src/auto/config.h
            #creates: src/auto/config.cache #This is created during failure as well

        - name: Make VIM
          command: make -j4 install
          args: 
            chdir: ./github/vim/
            creates: src/vim

        - name: Create bh Directory
          ansible.builtin.file: 
            path: "{{ ansible_env.HOME }}/bh/"
            state: directory

        - name: Copy Conf File 1
          ansible.builtin.copy: 
            src: "{{ playbook_dir }}/vimrc"
            dest: "{{ ansible_env.HOME }}/bh/"

        - name: Copy Conf File 2
          ansible.builtin.copy: 
            src: "{{ playbook_dir }}/cscope_maps.vim"
            dest: "{{ ansible_env.HOME }}/bh/"
            

